name = "berbirru"
main = "src/index.ts"
compatibility_date = "2025-06-01"

workers_dev = true

# [[routes]]
# pattern = "berbirru.com"
# custom_domain = true

[vars]
APP_NAME = "BERBIRRU"
APP_DOMAIN = "berbirru.com"

[observability]
enabled = true
